import type { LibraryRecipe } from './library'

/**
 * Phase 1 ("Homemade Protocol") recipe library — encoded from Chris's
 * Recipe Book + the meal-construction builds in the protocol doc.
 *
 * Every recipe here is Phase 1-legal: no breading, no deep-fry, no grains,
 * fruit, starchy veg, legumes, nuts, sugar, or alcohol. Dairy items (nonfat
 * Greek yogurt / cottage cheese) deviate from strict IP and are noted in the
 * protocol; they're included because they work.
 *
 * Macros are per single serving. The assembler scales servings to hit the
 * day's protein target.
 */

export const PHASE1_RECIPES: LibraryRecipe[] = [
  // ---------------------------------------------------------------- BREAKFAST
  {
    id: 'p1-denver-scramble',
    title: 'Denver scramble',
    protocols: ['phase1'],
    slots: ['breakfast'],
    servings: 1,
    macros: { kcal: 300, protein_g: 30, carbs_g: 8, fat_g: 16 },
    tags: ['savory', 'quick'],
    ingredients: [
      { item: 'Eggs', amount: '3 large', category: 'protein' },
      { item: 'Lean ground turkey (93%)', amount: '2 oz', category: 'protein' },
      { item: 'Bell pepper, diced', amount: '1/2 cup', category: 'produce' },
      { item: 'Onion, diced', amount: '2 tbsp', category: 'produce' },
      { item: 'Smoked paprika', amount: '1/2 tsp', category: 'spices' },
      { item: 'Olive oil', amount: '1 tsp', category: 'pantry' },
    ],
    steps: [
      'Brown the turkey with pepper and onion in the oil until cooked through.',
      'Beat the eggs, pour in, add smoked paprika, and scramble to set.',
      'Season with salt and pepper and serve hot.',
    ],
  },
  {
    id: 'p1-florentine-eggs',
    title: 'Florentine eggs',
    protocols: ['phase1'],
    slots: ['breakfast'],
    servings: 1,
    macros: { kcal: 260, protein_g: 22, carbs_g: 6, fat_g: 18 },
    tags: ['savory', 'quick'],
    ingredients: [
      { item: 'Eggs', amount: '3 large', category: 'protein' },
      { item: 'Spinach', amount: '2 cups', category: 'produce' },
      { item: 'Mushrooms, sliced', amount: '1/2 cup', category: 'produce' },
      { item: 'Olive oil', amount: '1 tsp', category: 'pantry' },
      { item: 'Black pepper, pinch nutmeg', amount: 'to taste', category: 'spices' },
    ],
    steps: [
      'Sauté mushrooms in the oil, then wilt the spinach.',
      'Add the beaten eggs and scramble softly.',
      'Finish with black pepper and a pinch of nutmeg.',
    ],
  },
  {
    id: 'p1-mexican-scramble',
    title: 'Mexican scramble',
    protocols: ['phase1'],
    slots: ['breakfast'],
    servings: 1,
    macros: { kcal: 250, protein_g: 22, carbs_g: 6, fat_g: 17 },
    tags: ['savory', 'quick'],
    ingredients: [
      { item: 'Eggs', amount: '3 large', category: 'protein' },
      { item: 'Hot peppers, chopped', amount: '2 tbsp', category: 'produce' },
      { item: 'Cilantro, chopped', amount: '2 tbsp', category: 'produce' },
      { item: 'Cumin', amount: '1/2 tsp', category: 'spices' },
      { item: 'Sugar-free salsa', amount: '2 tbsp', category: 'condiments' },
      { item: 'Sugar-free hot sauce', amount: 'to taste', category: 'condiments' },
    ],
    steps: [
      'Scramble the eggs with the hot peppers and cumin.',
      'Top with salsa, cilantro, and hot sauce.',
    ],
  },
  {
    id: 'p1-smoked-salmon-plate',
    title: 'Smoked salmon & cucumber plate',
    protocols: ['phase1'],
    slots: ['breakfast'],
    servings: 1,
    macros: { kcal: 230, protein_g: 25, carbs_g: 5, fat_g: 12 },
    tags: ['savory', 'no-cook'],
    ingredients: [
      { item: 'Smoked salmon (lox)', amount: '4 oz', category: 'protein' },
      { item: 'Cucumber, sliced', amount: '1 cup', category: 'produce' },
      { item: 'Red onion, thin', amount: '2 tbsp', category: 'produce' },
      { item: 'Capers', amount: '1 tsp', category: 'condiments' },
      { item: 'Dill + lemon', amount: 'to taste', category: 'produce' },
    ],
    steps: [
      'Arrange salmon with cucumber rounds and red onion.',
      'Scatter capers and dill; finish with a squeeze of lemon.',
    ],
  },
  {
    id: 'p1-frittata-muffins',
    title: 'Frittata muffins',
    protocols: ['phase1'],
    slots: ['breakfast', 'snack'],
    servings: 1,
    macros: { kcal: 180, protein_g: 16, carbs_g: 4, fat_g: 11 },
    tags: ['savory', 'batch'],
    ingredients: [
      { item: 'Eggs', amount: '2 large', category: 'protein' },
      { item: 'Chopped select vegetables', amount: '1/2 cup', category: 'produce' },
      { item: 'Salt & pepper', amount: 'to taste', category: 'spices' },
    ],
    steps: [
      'Whisk eggs with chopped veg, salt and pepper.',
      'Pour into muffin tin and bake at 375°F (190°C) ~18 min until set.',
      'Batch a dozen on Sunday; grab 2–3 on weekdays.',
    ],
  },

  // ------------------------------------------------------------------- LUNCH
  {
    id: 'p1-big-protein-salad',
    title: 'Big protein salad',
    protocols: ['phase1'],
    slots: ['lunch', 'dinner'],
    servings: 1,
    macros: { kcal: 330, protein_g: 40, carbs_g: 10, fat_g: 12 },
    tags: ['savory', 'no-cook'],
    ingredients: [
      { item: 'Cooked chicken breast, sliced', amount: '6 oz', category: 'protein' },
      { item: 'Romaine / arugula', amount: '3 cups', category: 'produce' },
      { item: 'Cucumber, radish, peppers', amount: '1.5 cups', category: 'produce' },
      { item: 'Lemon + vinegar', amount: '1 tbsp', category: 'condiments' },
      { item: 'Olive oil', amount: '1 tsp', category: 'pantry' },
    ],
    steps: [
      'Pile greens and raw veg in a bowl.',
      'Top with sliced protein.',
      'Dress with lemon, vinegar and the teaspoon of olive oil.',
    ],
  },
  {
    id: 'p1-tuna-lettuce-cups',
    title: 'Tuna no-mayo lettuce cups',
    protocols: ['phase1'],
    slots: ['lunch', 'snack'],
    servings: 1,
    macros: { kcal: 220, protein_g: 32, carbs_g: 6, fat_g: 4 },
    tags: ['savory', 'no-cook'],
    ingredients: [
      { item: 'Canned tuna in water (5 oz)', amount: '1 can', category: 'protein' },
      { item: 'Dijon mustard', amount: '1 tsp', category: 'condiments' },
      { item: 'Dill pickle, chopped', amount: '1 tbsp', category: 'condiments' },
      { item: 'Celery, diced', amount: '1 stalk', category: 'produce' },
      { item: 'Lettuce leaves', amount: '4 large', category: 'produce' },
      { item: 'Lemon + dill', amount: 'to taste', category: 'produce' },
    ],
    steps: [
      'Mix drained tuna with mustard, pickle, celery, lemon and dill.',
      'Spoon into lettuce cups and eat by hand.',
    ],
  },
  {
    id: 'p1-cold-shrimp-cocktail',
    title: 'Cold shrimp cocktail',
    protocols: ['phase1'],
    slots: ['lunch', 'snack'],
    servings: 1,
    macros: { kcal: 160, protein_g: 28, carbs_g: 6, fat_g: 2 },
    tags: ['savory', 'no-cook'],
    ingredients: [
      { item: 'Cooked shrimp', amount: '5 oz', category: 'protein' },
      { item: 'Sugar-free cocktail sauce', amount: '2 tbsp', category: 'condiments' },
      { item: 'Celery', amount: '2 stalks', category: 'produce' },
      { item: 'Lemon', amount: '1/2', category: 'produce' },
    ],
    steps: [
      'Pile shrimp on a plate with celery sticks.',
      'Squeeze lemon over and serve with cocktail sauce for dipping.',
    ],
  },
  {
    id: 'p1-cottage-crudite',
    title: 'Cottage cheese & crudité',
    protocols: ['phase1'],
    slots: ['lunch', 'snack', 'breakfast'],
    servings: 1,
    macros: { kcal: 150, protein_g: 26, carbs_g: 9, fat_g: 1 },
    tags: ['creamy', 'savory', 'no-cook'],
    ingredients: [
      { item: 'Nonfat cottage cheese', amount: '1 cup', category: 'dairy' },
      { item: 'Raw select veg dippers', amount: '1.5 cups', category: 'produce' },
      { item: 'Cracked pepper', amount: 'to taste', category: 'spices' },
    ],
    steps: ['Use the cottage cheese as a dip with raw veg; season with pepper.'],
  },

  // ------------------------------------------------------------------ DINNER
  {
    id: 'p1-mediterranean-chicken',
    title: 'Mediterranean grilled chicken',
    protocols: ['phase1'],
    slots: ['dinner'],
    servings: 1,
    macros: { kcal: 450, protein_g: 70, carbs_g: 12, fat_g: 14 },
    tags: ['savory'],
    ingredients: [
      { item: 'Chicken breast', amount: '8 oz', category: 'protein' },
      { item: 'Zucchini + asparagus', amount: '2 cups', category: 'produce' },
      { item: 'Lemon, oregano, garlic', amount: 'to taste', category: 'spices' },
      { item: 'Olive oil', amount: '1 tsp', category: 'pantry' },
    ],
    steps: [
      'Season chicken with lemon, oregano and garlic; grill or pan-sear.',
      'Sauté zucchini and asparagus in the oil.',
      'Finish with parsley and serve.',
    ],
  },
  {
    id: 'p1-cajun-cod',
    title: 'Cajun blackened cod',
    protocols: ['phase1'],
    slots: ['dinner'],
    servings: 1,
    macros: { kcal: 330, protein_g: 55, carbs_g: 10, fat_g: 8 },
    tags: ['savory'],
    ingredients: [
      { item: 'Cod fillet', amount: '8 oz', category: 'protein' },
      { item: 'Cajun seasoning (SF)', amount: '1 tbsp', category: 'spices' },
      { item: 'Cauliflower', amount: '2 cups', category: 'produce' },
      { item: 'Olive oil', amount: '1 tsp', category: 'pantry' },
    ],
    steps: [
      'Dry-rub the cod with Cajun seasoning; sear in a dry-to-light skillet.',
      'Roast or sauté the cauliflower with a little Cajun spice.',
    ],
  },
  {
    id: 'p1-asian-stir-fry',
    title: 'Ginger-garlic stir-fry',
    protocols: ['phase1'],
    slots: ['dinner'],
    servings: 1,
    macros: { kcal: 430, protein_g: 60, carbs_g: 14, fat_g: 16 },
    tags: ['savory'],
    ingredients: [
      { item: 'Sirloin or chicken, sliced', amount: '8 oz', category: 'protein' },
      { item: 'Bok choy, peppers, bean sprouts, mushroom', amount: '2.5 cups', category: 'produce' },
      { item: 'Coconut aminos', amount: '1 tbsp', category: 'condiments' },
      { item: 'Ginger + garlic', amount: 'to taste', category: 'spices' },
      { item: 'Olive oil', amount: '1 tsp', category: 'pantry' },
    ],
    steps: [
      'Sear the protein hot in the oil, then remove.',
      'Stir-fry the veg with ginger and garlic.',
      'Return protein, add coconut aminos, toss and serve.',
    ],
  },
  {
    id: 'p1-steakhouse-sirloin',
    title: 'Steakhouse sirloin',
    protocols: ['phase1'],
    slots: ['dinner'],
    servings: 1,
    macros: { kcal: 480, protein_g: 65, carbs_g: 10, fat_g: 20 },
    tags: ['savory'],
    ingredients: [
      { item: 'Sirloin or filet', amount: '8 oz', category: 'protein' },
      { item: 'Broccoli', amount: '2 cups', category: 'produce' },
      { item: 'Arugula salad', amount: '2 cups', category: 'produce' },
      { item: 'Olive oil', amount: '1 tsp', category: 'pantry' },
      { item: 'Garlic, salt, pepper', amount: 'to taste', category: 'spices' },
    ],
    steps: [
      'Sear the steak in the oil to your liking; rest it.',
      'Garlic-roast the broccoli.',
      'Serve with a big arugula salad.',
    ],
  },
  {
    id: 'p1-surf-scallops',
    title: 'Seared scallops, spinach',
    protocols: ['phase1'],
    slots: ['dinner'],
    servings: 1,
    macros: { kcal: 320, protein_g: 45, carbs_g: 12, fat_g: 9 },
    tags: ['savory'],
    ingredients: [
      { item: 'Scallops', amount: '8 oz', category: 'protein' },
      { item: 'Spinach', amount: '3 cups', category: 'produce' },
      { item: 'Green onion', amount: '2 stalks', category: 'produce' },
      { item: 'Olive oil', amount: '1 tsp', category: 'pantry' },
      { item: 'Lemon', amount: '1/2', category: 'produce' },
    ],
    steps: [
      'Sear scallops in the oil, 1–2 min per side; squeeze lemon.',
      'Sauté spinach and blistered green onion alongside.',
    ],
  },
  {
    id: 'p1-turkey-meatballs',
    title: 'Italian turkey meatballs & zoodles',
    protocols: ['phase1'],
    slots: ['dinner'],
    servings: 1,
    macros: { kcal: 400, protein_g: 50, carbs_g: 14, fat_g: 18 },
    tags: ['savory'],
    ingredients: [
      { item: 'Lean ground turkey (93%)', amount: '7 oz', category: 'protein' },
      { item: 'Egg (to bind)', amount: '1', category: 'protein' },
      { item: 'Zucchini, spiralized', amount: '2 cups', category: 'produce' },
      { item: 'Sugar-free marinara', amount: '1/2 cup', category: 'condiments' },
      { item: 'Italian herbs, garlic', amount: 'to taste', category: 'spices' },
    ],
    steps: [
      'Mix turkey with egg and herbs (no breadcrumb); roll meatballs and bake or pan-cook.',
      'Warm the marinara; serve over zucchini noodles.',
    ],
  },
  {
    id: 'p1-curry-shrimp',
    title: 'Curry shrimp & cauliflower',
    protocols: ['phase1'],
    slots: ['dinner'],
    servings: 1,
    macros: { kcal: 360, protein_g: 52, carbs_g: 14, fat_g: 10 },
    tags: ['savory'],
    ingredients: [
      { item: 'Shrimp (or chicken)', amount: '8 oz', category: 'protein' },
      { item: 'Cauliflower', amount: '2 cups', category: 'produce' },
      { item: 'Curry powder, turmeric, cumin', amount: '1 tbsp', category: 'spices' },
      { item: 'Crushed tomato (light)', amount: '1/3 cup', category: 'condiments' },
      { item: 'Olive oil', amount: '1 tsp', category: 'pantry' },
    ],
    steps: [
      'Bloom the spices in the oil, add light crushed tomato.',
      'Simmer the cauliflower in the sauce, then add shrimp until just cooked.',
    ],
  },
  {
    id: 'p1-taco-bowl',
    title: 'Taco bowl',
    protocols: ['phase1'],
    slots: ['dinner'],
    servings: 1,
    macros: { kcal: 360, protein_g: 45, carbs_g: 12, fat_g: 14 },
    tags: ['savory'],
    ingredients: [
      { item: 'Extra-lean ground beef or turkey', amount: '7 oz', category: 'protein' },
      { item: 'Shredded lettuce', amount: '2 cups', category: 'produce' },
      { item: 'Sugar-free salsa', amount: '2 tbsp', category: 'condiments' },
      { item: 'Sauerkraut', amount: '1/4 cup', category: 'produce' },
      { item: 'Taco spices, hot sauce', amount: 'to taste', category: 'spices' },
    ],
    steps: [
      'Brown the meat with taco spices in a dry pan.',
      'Pile over shredded lettuce; top with salsa, hot sauce and sauerkraut crunch.',
    ],
  },

  // ------------------------------------------------------- SNACKS: crunchy
  {
    id: 'p1-roasted-crisps',
    title: 'Roasted broccoli/cauliflower crisps',
    protocols: ['phase1'],
    slots: ['snack'],
    servings: 1,
    macros: { kcal: 90, protein_g: 4, carbs_g: 8, fat_g: 5 },
    tags: ['crunchy'],
    ingredients: [
      { item: 'Broccoli or cauliflower florets', amount: '2 cups', category: 'produce' },
      { item: 'Olive oil', amount: '1 tsp', category: 'pantry' },
      { item: 'Sea salt, smoked paprika, garlic powder', amount: '1 tsp', category: 'spices' },
    ],
    steps: [
      'Heat oven to 425°F (220°C). Pat florets bone-dry — that is the whole trick.',
      'Toss with oil and seasoning; spread in a single layer, not touching.',
      'Roast 22–28 min, flipping once, until edges are deep brown and crisp.',
    ],
  },
  {
    id: 'p1-cucumber-radish-chips',
    title: 'Cucumber & radish chips',
    protocols: ['phase1'],
    slots: ['snack'],
    servings: 1,
    macros: { kcal: 35, protein_g: 1, carbs_g: 6, fat_g: 0 },
    tags: ['crunchy', 'no-cook'],
    ingredients: [
      { item: 'Cucumber, thin-sliced', amount: '1 medium', category: 'produce' },
      { item: 'Radishes, thin-sliced', amount: '6', category: 'produce' },
      { item: 'Sea salt + SF chili-lime seasoning', amount: '3/4 tsp', category: 'spices' },
      { item: 'Lime', amount: '1/2', category: 'produce' },
    ],
    steps: [
      'Press slices between paper towels to pull moisture (5 min).',
      'Dust with salt and chili-lime; squeeze lime right before eating.',
    ],
  },
  {
    id: 'p1-pickles',
    title: 'Always-open pickle jar',
    protocols: ['phase1'],
    slots: ['snack'],
    servings: 1,
    macros: { kcal: 12, protein_g: 0, carbs_g: 2, fat_g: 0 },
    tags: ['crunchy', 'no-cook'],
    ingredients: [
      { item: 'Dill pickle spears (not sweet)', amount: '3', category: 'condiments' },
      { item: 'Red pepper flake, garlic (optional)', amount: 'to taste', category: 'spices' },
    ],
    steps: ['Keep a jar open in the fridge door — the reflex snack. Add chili/garlic to the brine for kick.'],
  },
  {
    id: 'p1-pork-rinds',
    title: 'Seasoned pork rinds',
    protocols: ['phase1'],
    slots: ['snack'],
    servings: 1,
    macros: { kcal: 150, protein_g: 16, carbs_g: 0, fat_g: 9 },
    tags: ['crunchy', 'no-cook'],
    ingredients: [
      { item: 'Plain pork rinds (chicharrones)', amount: '1 oz', category: 'pantry' },
      { item: 'Free seasoning (chili-lime / Cajun / pepper)', amount: '1/4 tsp', category: 'spices' },
    ],
    steps: ['Toss rinds with seasoning — zero-carb crunch with a real protein hit.'],
  },
  {
    id: 'p1-seaweed',
    title: 'Roasted seaweed snacks',
    protocols: ['phase1'],
    slots: ['snack'],
    servings: 1,
    macros: { kcal: 30, protein_g: 1, carbs_g: 1, fat_g: 2 },
    tags: ['crunchy', 'no-cook'],
    ingredients: [{ item: 'Roasted seaweed snacks (plain/sea-salt)', amount: '2 packs', category: 'pantry' }],
    steps: ['Eat straight from the pack, or crumble over a protein salad as a salty topper.'],
  },
  {
    id: 'p1-bell-pepper-nachos',
    title: 'Bell pepper "nachos"',
    protocols: ['phase1'],
    slots: ['snack', 'lunch'],
    servings: 1,
    macros: { kcal: 240, protein_g: 28, carbs_g: 10, fat_g: 11 },
    tags: ['savory', 'crunchy'],
    ingredients: [
      { item: 'Bell pepper, scoop-cut', amount: '1 large', category: 'produce' },
      { item: 'Extra-lean ground turkey (93%)', amount: '4 oz', category: 'protein' },
      { item: 'Cumin, chili, garlic powder', amount: '1 tsp', category: 'spices' },
      { item: 'Sugar-free salsa + hot sauce', amount: '1 tbsp', category: 'condiments' },
    ],
    steps: [
      'Brown the turkey with the spices in a dry pan.',
      'Spoon into pepper scoops; top with salsa, hot sauce and green onion.',
    ],
  },

  // ------------------------------------------------------- SNACKS: savory
  {
    id: 'p1-hard-eggs',
    title: 'Hard-boiled eggs',
    protocols: ['phase1'],
    slots: ['snack', 'breakfast'],
    servings: 1,
    macros: { kcal: 140, protein_g: 12, carbs_g: 1, fat_g: 10 },
    tags: ['savory', 'batch', 'no-cook'],
    ingredients: [
      { item: 'Eggs', amount: '2 large', category: 'protein' },
      { item: 'Salt, pepper, SF hot sauce', amount: 'to taste', category: 'spices' },
    ],
    steps: [
      'Boil, kill heat, cover 11 min, then ice-bath 5 min for clean peeling.',
      'Batch 8 on Sunday; store unpeeled up to a week.',
    ],
  },
  {
    id: 'p1-cold-shrimp',
    title: 'Cold shrimp with lemon',
    protocols: ['phase1'],
    slots: ['snack', 'lunch'],
    servings: 1,
    macros: { kcal: 130, protein_g: 24, carbs_g: 3, fat_g: 2 },
    tags: ['savory', 'no-cook'],
    ingredients: [
      { item: 'Cooked, peeled shrimp', amount: '4 oz', category: 'protein' },
      { item: 'Lemon', amount: '1/2', category: 'produce' },
      { item: 'SF hot/cocktail sauce', amount: '1 tbsp', category: 'condiments' },
      { item: 'Celery', amount: '1 stalk', category: 'produce' },
    ],
    steps: ['Squeeze lemon over the shrimp; serve with sauce and celery sticks.'],
  },
  {
    id: 'p1-turkey-rollups',
    title: 'Turkey & pickle roll-ups',
    protocols: ['phase1'],
    slots: ['snack', 'lunch'],
    servings: 1,
    macros: { kcal: 120, protein_g: 18, carbs_g: 3, fat_g: 4 },
    tags: ['savory', 'no-cook'],
    ingredients: [
      { item: 'Lean deli turkey (SF, low-sodium)', amount: '4 slices', category: 'protein' },
      { item: 'Dill pickle spears', amount: '4', category: 'condiments' },
      { item: 'Plain mustard (optional)', amount: '1 tsp', category: 'condiments' },
    ],
    steps: ['Smear turkey with a little mustard, roll around a pickle spear, halve into pinwheels.'],
  },
  {
    id: 'p1-tuna-boats',
    title: 'Tuna cucumber boats',
    protocols: ['phase1'],
    slots: ['snack', 'lunch'],
    servings: 1,
    macros: { kcal: 170, protein_g: 30, carbs_g: 6, fat_g: 2 },
    tags: ['savory', 'no-cook'],
    ingredients: [
      { item: 'Canned tuna in water (5 oz)', amount: '1 can', category: 'protein' },
      { item: 'Cucumber, halved & seeded', amount: '1 large', category: 'produce' },
      { item: 'Dijon mustard', amount: '1 tsp', category: 'condiments' },
      { item: 'Dill pickle, chopped', amount: '1 tbsp', category: 'condiments' },
      { item: 'Lemon, dill, salt, pepper', amount: 'to taste', category: 'spices' },
    ],
    steps: ['Mix tuna with mustard, pickle, lemon and dill; spoon into the cucumber halves.'],
  },
  {
    id: 'p1-savory-cottage-bowl',
    title: 'Savory cottage cheese bowl',
    protocols: ['phase1'],
    slots: ['snack', 'breakfast', 'lunch'],
    servings: 1,
    macros: { kcal: 150, protein_g: 26, carbs_g: 9, fat_g: 1 },
    tags: ['creamy', 'savory', 'no-cook'],
    ingredients: [
      { item: 'Nonfat cottage cheese', amount: '1 cup', category: 'dairy' },
      { item: 'Everything seasoning (SF) / pepper', amount: '1/2 tsp', category: 'spices' },
      { item: 'Cucumber, diced', amount: '1/2', category: 'produce' },
    ],
    steps: ['Top cottage cheese with seasoning, cucumber and hot sauce; stir and eat.'],
  },

  // ------------------------------------------------------- SNACKS: creamy
  {
    id: 'p1-yogurt-soft-serve',
    title: 'Greek yogurt soft-serve',
    protocols: ['phase1'],
    slots: ['snack', 'breakfast'],
    servings: 1,
    macros: { kcal: 130, protein_g: 23, carbs_g: 9, fat_g: 0 },
    tags: ['creamy'],
    ingredients: [
      { item: 'Nonfat plain Greek yogurt', amount: '1 cup', category: 'dairy' },
      { item: 'Stevia / monk fruit', amount: '1/2 tsp', category: 'pantry' },
      { item: 'Vanilla extract', amount: '1/2 tsp', category: 'pantry' },
    ],
    steps: [
      'Stir yogurt with sweetener and vanilla.',
      'Freeze 60–90 min, stirring every 20 min — or freeze fully then blend for soft-serve.',
    ],
  },
  {
    id: 'p1-yogurt-bark',
    title: 'Frozen yogurt bark',
    protocols: ['phase1'],
    slots: ['snack'],
    servings: 1,
    macros: { kcal: 70, protein_g: 12, carbs_g: 5, fat_g: 0 },
    tags: ['creamy', 'batch'],
    ingredients: [
      { item: 'Nonfat plain Greek yogurt', amount: '1/2 cup', category: 'dairy' },
      { item: 'Stevia + vanilla', amount: 'to taste', category: 'pantry' },
      { item: 'Cinnamon (optional)', amount: 'pinch', category: 'spices' },
    ],
    steps: [
      'Spread sweetened yogurt 1/4-inch thick on parchment; dust with cinnamon.',
      'Freeze 3+ hours, break into shards, store in a freezer bag.',
    ],
  },
  {
    id: 'p1-protein-mousse',
    title: 'Protein mousse',
    protocols: ['phase1'],
    slots: ['snack', 'breakfast'],
    servings: 1,
    macros: { kcal: 150, protein_g: 28, carbs_g: 10, fat_g: 0 },
    tags: ['creamy'],
    ingredients: [
      { item: 'Nonfat Greek yogurt (or vanilla whey)', amount: '3/4 cup', category: 'dairy' },
      { item: 'Vanilla + sweetener', amount: 'to taste', category: 'pantry' },
      { item: 'Cinnamon', amount: '1/2 tsp', category: 'spices' },
    ],
    steps: ['Whip until airy, fold in vanilla, sweetener and cinnamon; chill 10 min.'],
  },
  {
    id: 'p1-cottage-pudding',
    title: 'Whipped cottage cheese pudding',
    protocols: ['phase1'],
    slots: ['snack', 'breakfast'],
    servings: 1,
    macros: { kcal: 150, protein_g: 26, carbs_g: 9, fat_g: 1 },
    tags: ['creamy', 'batch'],
    ingredients: [
      { item: 'Nonfat cottage cheese', amount: '1 cup', category: 'dairy' },
      { item: 'Vanilla + sweetener', amount: 'to taste', category: 'pantry' },
      { item: 'Cinnamon', amount: '1/4 tsp', category: 'spices' },
    ],
    steps: ['Blend completely smooth (that is what makes it pudding), then add vanilla and cinnamon; chill.'],
  },
]
