import { useEffect } from 'react'
import { useStore } from './store'
import { Disclaimer } from './components/Disclaimer'
import { IntakeForm } from './components/IntakeForm'
import { TargetsReview } from './components/TargetsReview'
import { PlanView } from './components/PlanView'
import { SavedPlans } from './components/SavedPlans'

export default function App() {
  const view = useStore((s) => s.view)
  const init = useStore((s) => s.init)
  const goto = useStore((s) => s.goto)
  const savedCount = useStore((s) => s.savedPlans.length)
  const hasProfile = useStore((s) => s.profile !== null)

  useEffect(() => {
    void init()
  }, [init])

  return (
    <div className="min-h-screen">
      <Disclaimer />
      <header className="no-print border-b border-stone-200 bg-white/70 backdrop-blur">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-3">
          <button onClick={() => goto(hasProfile ? 'review' : 'intake')} className="flex items-center gap-2">
            <span className="text-2xl" aria-hidden>
              🔥
            </span>
            <span className="text-xl font-display font-semibold text-stone-800">MealForge</span>
          </button>
          <nav className="flex items-center gap-2 text-sm">
            <button
              onClick={() => goto('intake')}
              className={`rounded-md px-3 py-1.5 ${view === 'intake' ? 'bg-forge-50 text-forge-700' : 'text-stone-600 hover:bg-stone-100'}`}
            >
              New plan
            </button>
            {hasProfile && (
              <button
                onClick={() => goto('review')}
                className={`rounded-md px-3 py-1.5 ${view === 'review' || view === 'plan' ? 'bg-forge-50 text-forge-700' : 'text-stone-600 hover:bg-stone-100'}`}
              >
                Current
              </button>
            )}
            <button
              onClick={() => goto('saved')}
              className={`rounded-md px-3 py-1.5 ${view === 'saved' ? 'bg-forge-50 text-forge-700' : 'text-stone-600 hover:bg-stone-100'}`}
            >
              Saved{savedCount > 0 ? ` (${savedCount})` : ''}
            </button>
          </nav>
        </div>
      </header>

      <main>
        {view === 'intake' && <IntakeForm />}
        {view === 'review' && <TargetsReview />}
        {view === 'plan' && <PlanView />}
        {view === 'saved' && <SavedPlans />}
      </main>

      <footer className="no-print mx-auto max-w-5xl px-4 py-10 text-center text-xs text-stone-400">
        MealForge · targets computed transparently in code · recipes generated by Claude
      </footer>
    </div>
  )
}
